
import React from 'react';

export const primaryBlue = '#3B82F6';
export const primaryPink = '#EC4899';
export const bgLight = '#F8FAFC';
export const borderLight = '#E2E8F0';
export const textPrimary = '#1E293B';
export const textSecondary = '#64748B';

export const styles: { [key: string]: React.CSSProperties } = {
    appContainer: {
        minHeight: '100vh',
        position: 'relative',
        color: textPrimary,
        backgroundColor: '#F1F5F9',
        fontFamily: "'Noto Sans JP', sans-serif",
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '0.75rem 1.25rem',
        backgroundColor: '#FFFFFF',
        borderBottom: `1px solid ${borderLight}`,
        position: 'sticky',
        top: 0,
        zIndex: 1000,
    },
    logo: {
        margin: 0,
        fontSize: '1.4rem',
        fontWeight: '900',
        color: '#1E293B',
        letterSpacing: '-0.02em',
    },
    headerAvatar: {
        width: '36px',
        height: '36px',
        borderRadius: '50%',
        backgroundColor: '#F1F5F9',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '0.8rem',
        fontWeight: 'bold',
        color: textSecondary,
    },
    main: { 
        paddingBottom: '120px' 
    },
    campusWallTabs: {
        display: 'flex',
        backgroundColor: '#FFFFFF',
        padding: '0 1.25rem',
        borderBottom: `1px solid ${borderLight}`,
        gap: '1.5rem',
    },
    wallTab: {
        padding: '0.75rem 0',
        border: 'none',
        backgroundColor: 'transparent',
        fontSize: '0.95rem',
        fontWeight: '700',
        color: '#94A3B8',
        cursor: 'pointer',
        position: 'relative',
        transition: 'color 0.2s',
    },
    wallTabActive: {
        color: primaryBlue,
    },
    tabIndicator: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: '3px',
        backgroundColor: primaryBlue,
        borderRadius: '3px 3px 0 0',
    },
    boardSelector: {
        margin: '0.75rem 1rem',
        padding: '0.8rem 1.25rem',
        backgroundColor: '#FFFFFF',
        borderRadius: '12px',
        border: `1px solid ${borderLight}`,
        display: 'flex',
        alignItems: 'center',
        gap: '0.75rem',
        color: '#64748B',
        fontSize: '0.9rem',
        fontWeight: '500',
        cursor: 'pointer',
        boxShadow: '0 2px 8px rgba(0,0,0,0.02)',
    },
    postList: { 
        display: 'flex', 
        flexDirection: 'column', 
        gap: '1rem',
        padding: '0 1rem'
    },
    card: {
        background: '#FFFFFF',
        borderRadius: '24px',
        padding: '1.25rem',
        boxShadow: '0 2px 12px rgba(0, 0, 0, 0.03)',
        border: `1px solid ${borderLight}`,
    },
    cardHeader: { 
        display: 'flex', 
        alignItems: 'center', 
        gap: '0.75rem', 
        marginBottom: '0.75rem' 
    },
    avatar: { 
        width: '44px', 
        height: '44px', 
        borderRadius: '50%', 
        backgroundColor: '#E2E8F0',
        backgroundSize: 'cover',
        backgroundPosition: 'center',
        flexShrink: 0,
    },
    authorName: { fontWeight: '800', color: textPrimary, fontSize: '1rem' },
    timestamp: { fontSize: '0.85rem', color: '#94A3B8', marginTop: '1px' },
    cardContent: { 
        margin: '0 0 1rem 0', 
        color: '#334155', 
        fontSize: '1.05rem', 
        lineHeight: '1.6',
        whiteSpace: 'pre-wrap',
    },
    tagContainer: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '0.5rem',
        marginBottom: '1rem',
    },
    tag: {
        padding: '0.4rem 0.75rem',
        backgroundColor: '#EFF6FF',
        color: primaryBlue,
        borderRadius: '10px',
        fontSize: '0.85rem',
        fontWeight: '700',
    },
    cardFooter: {
        display: 'flex',
        alignItems: 'center',
        paddingTop: '0.75rem',
        borderTop: `1px solid #F8FAFC`,
        gap: '1.5rem',
    },
    footerAction: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.5rem',
        color: '#94A3B8',
        fontSize: '0.9rem',
        fontWeight: '600',
        cursor: 'pointer',
    },
    fab: {
        position: 'fixed',
        bottom: '100px',
        right: '1.5rem',
        width: '60px',
        height: '60px',
        borderRadius: '50%',
        background: primaryBlue,
        color: '#fff',
        border: 'none',
        fontSize: '2rem',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        boxShadow: `0 8px 16px rgba(59, 130, 246, 0.3)`,
        cursor: 'pointer',
        zIndex: 999,
    },
    navBar: {
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        height: '85px',
        backgroundColor: '#FFFFFF',
        borderTop: `1px solid ${borderLight}`,
        display: 'flex',
        justifyContent: 'space-around',
        alignItems: 'center',
        zIndex: 1000,
        paddingBottom: 'env(safe-area-inset-bottom)',
    },
    navItem: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '4px',
        background: 'none',
        border: 'none',
        color: '#94A3B8',
        cursor: 'pointer',
        padding: '8px',
        flex: 1,
    },
    activeNavItem: {
        color: primaryBlue,
    },
    activeNavBox: {
        padding: '4px 12px',
        borderRadius: '12px',
        border: `2px solid ${primaryBlue}`,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        transition: 'all 0.2s',
    },
    navLabel: { fontSize: '0.75rem', fontWeight: '800' },
    reelContainer: { 
        height: '100vh', 
        overflowY: 'auto', 
        scrollSnapType: 'y mandatory', 
        backgroundColor: '#000',
        scrollbarWidth: 'none',
    },
    reelItem: { 
        height: '100vh', 
        position: 'relative', 
        scrollSnapAlign: 'start', 
        overflow: 'hidden' 
    },
    reelBg: { 
        width: '100%', 
        height: '100%', 
        objectFit: 'cover' 
    },
    reelOverlay: { 
        position: 'absolute', 
        bottom: '125px', 
        left: 0, 
        right: 0, 
        padding: '1.5rem', 
        color: '#fff',
        zIndex: 10,
    },
    businessCard: { 
        background: '#FFFFFF', 
        borderRadius: '28px', 
        overflow: 'hidden', 
        boxShadow: '0 12px 30px rgba(0,0,0,0.06)', 
        margin: '1rem',
        border: `1px solid ${borderLight}`
    },
    cardContentContainer: { padding: '2.5rem 1.5rem', textAlign: 'center' },
    profileAvatar: { 
        width: '100px', 
        height: '100px', 
        borderRadius: '50%', 
        backgroundColor: '#F1F5F9', 
        margin: '0 auto 1.25rem', 
        overflow: 'hidden', 
        backgroundSize: 'cover', 
        backgroundPosition: 'center' 
    },
    userName: { fontSize: '1.5rem', fontWeight: '900', margin: '0 0 0.5rem', color: textPrimary },
    userTitle: { fontSize: '0.9rem', color: textSecondary, margin: '0 0 1.25rem', fontWeight: '600' },
    userInfoSeparator: { height: '4px', backgroundColor: primaryBlue, opacity: 0.1, width: '40px', margin: '0 auto 1.25rem', borderRadius: '2px' },
    userUniversity: { fontSize: '1.1rem', fontWeight: '800', margin: '0 0 0.25rem', color: textPrimary },
    userDepartment: { fontSize: '0.85rem', color: textSecondary, margin: '0 0 1.5rem' },
    snsLinks: { display: 'flex', justifyContent: 'center', gap: '1.5rem', marginBottom: '0.5rem' },
    snsIcon: { color: textSecondary, transition: 'color 0.2s' },
    qrSection: { backgroundColor: '#F8FAFC', padding: '1.5rem', textAlign: 'center', borderTop: `1px solid ${borderLight}` },
    qrCode: { width: '80px', height: '80px', margin: '0 auto 1rem', opacity: 0.7 },
    shareButton: { background: 'none', border: 'none', color: primaryBlue, fontWeight: '800', fontSize: '0.9rem', cursor: 'pointer' },

    // Added missing styles
    messagesPage: {
        display: 'flex',
        flexDirection: 'column',
        height: '100vh',
        backgroundColor: '#F8FAFC',
    },
    messagesHeader: {
        padding: '1.5rem',
        backgroundColor: '#FFFFFF',
        borderBottom: `1px solid ${borderLight}`,
    },
    messagesTitle: {
        fontSize: '1.6rem',
        fontWeight: '900',
        margin: 0,
        color: textPrimary,
    },
    tabsContainer: {
        display: 'flex',
        gap: '1rem',
        overflowX: 'auto',
    },
    tab: {
        padding: '0.6rem 1.25rem',
        borderRadius: '20px',
        border: `1.5px solid ${borderLight}`,
        backgroundColor: 'transparent',
        fontSize: '0.9rem',
        fontWeight: '700',
        color: textSecondary,
        cursor: 'pointer',
        whiteSpace: 'nowrap',
    },
    activeTab: {
        backgroundColor: primaryBlue,
        color: '#FFFFFF',
        borderColor: primaryBlue,
    },
    searchBarContainer: {
        padding: '1rem 1.5rem',
    },
    searchBar: {
        width: '100%',
        padding: '0.8rem 1.25rem',
        borderRadius: '16px',
        border: `1.5px solid ${borderLight}`,
        fontSize: '0.95rem',
        outline: 'none',
        backgroundColor: '#FFFFFF',
    },
    listItem: {
        display: 'flex',
        alignItems: 'center',
        padding: '1rem',
        backgroundColor: '#FFFFFF',
        borderRadius: '18px',
        marginBottom: '0.75rem',
        border: `1px solid ${borderLight}`,
        gap: '1rem',
        cursor: 'pointer',
    },
    listInfo: {
        flex: 1,
        minWidth: 0,
    },
    listTitle: {
        fontWeight: '800',
        fontSize: '1rem',
        color: textPrimary,
        margin: 0,
    },
    listSubtitle: {
        fontSize: '0.85rem',
        color: textSecondary,
        margin: '2px 0 0',
        whiteSpace: 'nowrap',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
    },
    button: {
        padding: '0.6rem 1.25rem',
        borderRadius: '12px',
        border: 'none',
        fontWeight: '700',
        fontSize: '0.9rem',
        cursor: 'pointer',
    },
    signupButton: {
        backgroundColor: primaryBlue,
        color: '#FFFFFF',
        width: '100%',
        padding: '1rem',
        borderRadius: '16px',
        fontSize: '1rem',
        fontWeight: '800',
        marginTop: '1rem',
    },
    profilePage: {
        minHeight: '100vh',
        backgroundColor: '#F8FAFC',
        paddingBottom: '120px',
    },
    profileHeader: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '1rem 1.25rem',
        backgroundColor: '#FFFFFF',
        borderBottom: `1px solid ${borderLight}`,
        position: 'sticky',
        top: 0,
        zIndex: 100,
    },
    backButton: {
        background: 'none',
        border: 'none',
        color: textPrimary,
        padding: '4px',
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
    },
    profileTitle: {
        fontSize: '1.1rem',
        fontWeight: '800',
        margin: 0,
    },
    userListItem: {
        display: 'flex',
        alignItems: 'center',
        padding: '1rem',
        backgroundColor: '#FFFFFF',
        borderRadius: '20px',
        marginBottom: '0.75rem',
        border: `1px solid ${borderLight}`,
        gap: '1rem',
        cursor: 'pointer',
    },
    followButton: {
        padding: '0.5rem 1rem',
        borderRadius: '12px',
        fontSize: '0.8rem',
        fontWeight: '800',
        cursor: 'pointer',
        border: '2px solid transparent',
    },
    followButtonActive: {
        backgroundColor: 'transparent',
        borderColor: borderLight,
        color: textSecondary,
    },
    followButtonInactive: {
        backgroundColor: primaryBlue,
        color: '#FFFFFF',
    },
    chatScreen: {
        display: 'flex',
        flexDirection: 'column',
        height: '100vh',
        backgroundColor: '#F1F5F9',
    },
    chatScreenHeader: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '0.75rem 1rem',
        backgroundColor: '#FFFFFF',
        borderBottom: `1px solid ${borderLight}`,
    },
    chatPartnerName: {
        fontSize: '1.1rem',
        fontWeight: '800',
        margin: 0,
    },
    messageList: {
        flex: 1,
        overflowY: 'auto',
        padding: '1.5rem',
        display: 'flex',
        flexDirection: 'column',
        gap: '1rem',
    },
    myMessage: {
        alignSelf: 'flex-end',
        backgroundColor: primaryBlue,
        color: '#FFFFFF',
        padding: '0.8rem 1.2rem',
        borderRadius: '20px 20px 4px 20px',
        maxWidth: '80%',
        boxShadow: '0 4px 12px rgba(59, 130, 246, 0.2)',
    },
    theirMessage: {
        alignSelf: 'flex-start',
        backgroundColor: '#FFFFFF',
        color: textPrimary,
        padding: '0.8rem 1.2rem',
        borderRadius: '20px 20px 20px 4px',
        maxWidth: '80%',
        boxShadow: '0 4px 12px rgba(0,0,0,0.03)',
    },
    messageText: {
        margin: 0,
        fontSize: '1rem',
        lineHeight: '1.5',
    },
    messageTimestamp: {
        fontSize: '0.7rem',
        opacity: 0.7,
        marginTop: '4px',
        display: 'block',
        textAlign: 'right',
    },
    theirMessageTimestamp: {
        fontSize: '0.7rem',
        color: textSecondary,
        marginTop: '4px',
        display: 'block',
    },
    messageInputForm: {
        padding: '1rem',
        backgroundColor: '#FFFFFF',
        borderTop: `1px solid ${borderLight}`,
        display: 'flex',
        gap: '0.75rem',
    },
    messageInput: {
        flex: 1,
        padding: '0.8rem 1.25rem',
        borderRadius: '24px',
        border: `1.5px solid ${borderLight}`,
        fontSize: '0.95rem',
        outline: 'none',
        backgroundColor: '#F8FAFC',
    },
    sendButton: {
        backgroundColor: primaryBlue,
        color: '#FFFFFF',
        border: 'none',
        padding: '0 1.5rem',
        borderRadius: '24px',
        fontWeight: '800',
        cursor: 'pointer',
    },
    modalOverlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.5)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 2000,
        padding: '1.5rem',
    },
    modalContent: {
        backgroundColor: '#FFFFFF',
        borderRadius: '32px',
        width: '100%',
        maxWidth: '500px',
        padding: '2rem',
        boxShadow: '0 25px 50px -12px rgba(0,0,0,0.25)',
    },
    modalHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '1.5rem',
    },
    modalTitle: {
        fontSize: '1.4rem',
        fontWeight: '900',
        margin: 0,
    },
    closeButton: {
        background: 'none',
        border: 'none',
        fontSize: '1.5rem',
        cursor: 'pointer',
        color: textSecondary,
    },
    modalForm: {
        display: 'flex',
        flexDirection: 'column',
        gap: '1rem',
    },
    modalInput: {
        padding: '1rem',
        borderRadius: '16px',
        border: `1.5px solid ${borderLight}`,
        fontSize: '1rem',
        outline: 'none',
        width: '100%',
    },
    modalTextarea: {
        minHeight: '150px',
        resize: 'none',
    },
    businessCardPage: {
        minHeight: '100vh',
        backgroundColor: '#F8FAFC',
        padding: '1.5rem 1.5rem 120px 1.5rem',
    },
};
